// Package inbetween is the independent Go implementation of the in-between module (REQ-TEST-003).
// It MUST be byte-identical to the TypeScript engine: same transitions, same settlement, same
// canonical state hash. The differential corpus (generated by TS) is replayed here and every hash
// is compared. Any divergence is a consensus bug and fails the build.
package inbetween

import (
	"math/big"
	"sort"

	"bsvuniversal/canonical"
)

type Ruleset struct {
	MinBet, MaxBet, Ante, EqualVisiblePenalty            *big.Int
	PostPenaltyMultiplier, DecisionTimeout, RecoveryTimeout, MinPlayers, MaxPlayers int
}

type Bal struct {
	Party string
	Amt   *big.Int
}

type State struct {
	GameID          string
	RulesetHash     string
	Ruleset         Ruleset
	Parties         []string
	Balances        []Bal
	Pot             *big.Int
	Total           *big.Int
	RoundNo         int
	ActingIdx       int
	Phase           string // deck-commitment | await-bet | complete
	Visible         *[2]int
	Third           *int
	LastOutcome     *string
	RoundsRemaining int
}

func u32be(n int) []byte {
	return []byte{byte(n >> 24), byte(n >> 16), byte(n >> 8), byte(n)}
}

// DrawValue mirrors crypto.drawValue: rejection sampling over TaggedHash(beacon, seed,label,counter).
func DrawValue(seed []byte, label, modulus int) int {
	limit := (256 / modulus) * modulus
	for counter := 0; counter < 1<<24; counter++ {
		block := canonical.TaggedHash(canonical.TagBeacon, seed, u32be(label), u32be(counter))
		for _, b := range block {
			if int(b) < limit {
				return int(b) % modulus
			}
		}
	}
	panic("drawValue exhausted")
}

func sortBalances(bs []Bal) []Bal {
	out := make([]Bal, len(bs))
	copy(out, bs)
	sort.SliceStable(out, func(i, j int) bool { return out[i].Party < out[j].Party }) // codepoint order
	return out
}

func bal(s *State, party string) *big.Int {
	for _, b := range s.Balances {
		if b.Party == party {
			return new(big.Int).Set(b.Amt)
		}
	}
	return big.NewInt(0)
}

func withBalance(s *State, party string, v *big.Int) []Bal {
	out := make([]Bal, len(s.Balances))
	for i, b := range s.Balances {
		if b.Party == party {
			out[i] = Bal{Party: b.Party, Amt: v}
		} else {
			out[i] = Bal{Party: b.Party, Amt: new(big.Int).Set(b.Amt)}
		}
	}
	return sortBalances(out)
}

func cloneBalances(bs []Bal) []Bal {
	out := make([]Bal, len(bs))
	for i, b := range bs {
		out[i] = Bal{Party: b.Party, Amt: new(big.Int).Set(b.Amt)}
	}
	return out
}

func rulesetObj(r Ruleset) *canonical.Obj {
	return canonical.NewObj().
		Set("minBet", r.MinBet).Set("maxBet", r.MaxBet).Set("ante", r.Ante).
		Set("equalVisiblePenalty", r.EqualVisiblePenalty).Set("postPenaltyMultiplier", r.PostPenaltyMultiplier).
		Set("decisionTimeout", r.DecisionTimeout).Set("recoveryTimeout", r.RecoveryTimeout).
		Set("minPlayers", r.MinPlayers).Set("maxPlayers", r.MaxPlayers)
}

func rulesetHashHex(r Ruleset) string {
	h := canonical.TaggedHash(canonical.TagRuleset, []byte(canonical.Stringify(rulesetObj(r))))
	return toHex(h)
}

func toHex(b []byte) string {
	const hexd = "0123456789abcdef"
	out := make([]byte, len(b)*2)
	for i, x := range b {
		out[i*2] = hexd[x>>4]
		out[i*2+1] = hexd[x&0xf]
	}
	return string(out)
}

// Init mirrors initInBetween.
func Init(gameID string, parties []string, startingStack *big.Int, roundsTotal int, r Ruleset) *State {
	bs := make([]Bal, len(parties))
	for i, p := range parties {
		bs[i] = Bal{Party: p, Amt: new(big.Int).Sub(startingStack, r.Ante)}
	}
	pot := new(big.Int).Mul(r.Ante, big.NewInt(int64(len(parties))))
	total := new(big.Int).Mul(startingStack, big.NewInt(int64(len(parties))))
	return &State{
		GameID: gameID, RulesetHash: rulesetHashHex(r), Ruleset: r,
		Parties: append([]string{}, parties...), Balances: sortBalances(bs),
		Pot: pot, Total: total, RoundNo: 1, ActingIdx: 0, Phase: "deck-commitment",
		RoundsRemaining: roundsTotal,
	}
}

// StateValue builds the canonical value tree for the state (sorted keys via Stringify).
func StateValue(s *State) canonical.Value {
	balances := make([]canonical.Value, len(s.Balances))
	for i, b := range s.Balances {
		balances[i] = []canonical.Value{b.Party, b.Amt}
	}
	parties := make([]canonical.Value, len(s.Parties))
	for i, p := range s.Parties {
		parties[i] = p
	}
	o := canonical.NewObj().
		Set("module", "in-between").Set("gameId", s.GameID).Set("rulesetHash", s.RulesetHash).
		Set("ruleset", rulesetObj(s.Ruleset)).Set("parties", []canonical.Value(parties)).
		Set("balances", []canonical.Value(balances)).Set("pot", s.Pot).Set("total", s.Total).
		Set("roundNo", s.RoundNo).Set("actingIdx", s.ActingIdx).Set("phase", s.Phase).
		Set("roundsRemaining", s.RoundsRemaining)
	if s.Visible != nil {
		o.Set("visible", []canonical.Value{s.Visible[0], s.Visible[1]})
	} else {
		o.Set("visible", nil)
	}
	if s.Third != nil {
		o.Set("third", *s.Third)
	} else {
		o.Set("third", nil)
	}
	if s.LastOutcome != nil {
		o.Set("lastOutcome", *s.LastOutcome)
	} else {
		o.Set("lastOutcome", nil)
	}
	return o
}

func HashHex(s *State) string { return toHex(canonical.Hash(StateValue(s))) }

// CanonString exposes the canonical JSON (for debugging differential mismatches).
func CanonString(s *State) string { return canonical.Stringify(StateValue(s)) }

func advance(s *State, outcome string, balances []Bal, pot *big.Int) *State {
	rr := s.RoundsRemaining - 1
	done := rr <= 0 || pot.Sign() <= 0
	phase := "deck-commitment"
	if done {
		phase = "complete"
	}
	oc := outcome
	return &State{
		GameID: s.GameID, RulesetHash: s.RulesetHash, Ruleset: s.Ruleset, Parties: s.Parties,
		Balances: sortBalances(balances), Pot: pot, Total: s.Total,
		RoundNo: s.RoundNo + 1, ActingIdx: (s.ActingIdx + 1) % len(s.Parties), Phase: phase,
		Visible: nil, Third: nil, LastOutcome: &oc, RoundsRemaining: rr,
	}
}

func legalMax(s *State) *big.Int {
	acting := s.Parties[s.ActingIdx]
	mul := s.Ruleset.PostPenaltyMultiplier
	if mul < 1 {
		mul = 1
	}
	byBalance := new(big.Int).Div(bal(s, acting), big.NewInt(int64(mul)))
	m := new(big.Int).Set(s.Ruleset.MaxBet)
	if s.Pot.Cmp(m) < 0 {
		m = new(big.Int).Set(s.Pot)
	}
	if byBalance.Cmp(m) < 0 {
		m = byBalance
	}
	return m
}

func resolveBet(s *State, amount *big.Int) *State {
	acting := s.Parties[s.ActingIdx]
	lo, hi := s.Visible[0], s.Visible[1]
	third := *s.Third
	var balances []Bal
	var pot *big.Int
	var outcome string
	if third > lo && third < hi {
		balances = withBalance(s, acting, new(big.Int).Add(bal(s, acting), amount))
		pot = new(big.Int).Sub(s.Pot, amount)
		outcome = "win"
	} else if third == lo || third == hi {
		pay := new(big.Int).Mul(amount, big.NewInt(int64(s.Ruleset.PostPenaltyMultiplier)))
		balances = withBalance(s, acting, new(big.Int).Sub(bal(s, acting), pay))
		pot = new(big.Int).Add(s.Pot, pay)
		outcome = "loss-post"
	} else {
		balances = withBalance(s, acting, new(big.Int).Sub(bal(s, acting), amount))
		pot = new(big.Int).Add(s.Pot, amount)
		outcome = "loss"
	}
	return advance(s, outcome, balances, pot)
}

// Step mirrors the engine Step.
type Step struct {
	Kind    string
	SeedHex string
	Branch  string
	Action  *Action
}
type Action struct {
	Type   string
	Party  string
	Amount *big.Int
}

// Apply mirrors inBetweenModule.apply. Returns (next, ok, reason). Total: never panics on bad input.
func Apply(s *State, step Step) (*State, bool, string) {
	if s.Phase == "complete" {
		return nil, false, "game complete"
	}
	switch step.Kind {
	case "randomness":
		if s.Phase != "deck-commitment" {
			return nil, false, "randomness not expected"
		}
		seed, ok := fromHex(step.SeedHex)
		if !ok || len(seed) != 32 {
			return nil, false, "bad seed"
		}
		a := DrawValue(seed, 1, 13) + 1
		b := DrawValue(seed, 2, 13) + 1
		third := DrawValue(seed, 3, 13) + 1
		lo, hi := a, b
		if lo > hi {
			lo, hi = hi, lo
		}
		if lo == hi {
			acting := s.Parties[s.ActingIdx]
			pen := s.Ruleset.EqualVisiblePenalty
			return advance(s, "equal-visible-penalty", withBalance(s, acting, new(big.Int).Sub(bal(s, acting), pen)), new(big.Int).Add(s.Pot, pen)), true, ""
		}
		if hi-lo == 1 {
			return advance(s, "consecutive-auto-pass", cloneBalances(s.Balances), new(big.Int).Set(s.Pot)), true, ""
		}
		v := [2]int{lo, hi}
		ns := *s
		ns.Visible = &v
		ns.Third = &third
		ns.Phase = "await-bet"
		ns.Balances = cloneBalances(s.Balances)
		ns.Pot = new(big.Int).Set(s.Pot)
		return &ns, true, ""
	case "timeout":
		if s.Phase != "await-bet" {
			return nil, false, "no timeout branch"
		}
		if step.Branch != "pass" {
			return nil, false, "unknown timeout branch"
		}
		return advance(s, "timeout-pass", cloneBalances(s.Balances), new(big.Int).Set(s.Pot)), true, ""
	case "action":
		if s.Phase != "await-bet" {
			return nil, false, "no action expected"
		}
		acting := s.Parties[s.ActingIdx]
		if step.Action == nil || step.Action.Party != acting {
			return nil, false, "non-acting party"
		}
		if step.Action.Type == "PASS" {
			return advance(s, "pass", cloneBalances(s.Balances), new(big.Int).Set(s.Pot)), true, ""
		}
		if step.Action.Type == "BET" {
			if step.Action.Amount == nil {
				return nil, false, "BET requires amount"
			}
			max := legalMax(s)
			if step.Action.Amount.Cmp(s.Ruleset.MinBet) < 0 || step.Action.Amount.Cmp(max) > 0 {
				return nil, false, "bet out of range"
			}
			return resolveBet(s, step.Action.Amount), true, ""
		}
		return nil, false, "unknown action"
	default:
		return nil, false, "unknown step kind"
	}
}

// Settle mirrors module.settle.
func Settle(s *State) (map[string]string, bool) {
	out := map[string]string{}
	sum := big.NewInt(0)
	for _, b := range s.Balances {
		out[b.Party] = b.Amt.String()
		sum.Add(sum, b.Amt)
	}
	conserved := new(big.Int).Add(sum, s.Pot).Cmp(s.Total) == 0
	return out, conserved
}

func fromHex(h string) ([]byte, bool) {
	if len(h)%2 != 0 {
		return nil, false
	}
	out := make([]byte, len(h)/2)
	for i := 0; i < len(out); i++ {
		hi, ok1 := hexNib(h[i*2])
		lo, ok2 := hexNib(h[i*2+1])
		if !ok1 || !ok2 {
			return nil, false
		}
		out[i] = hi<<4 | lo
	}
	return out, true
}

func hexNib(c byte) (byte, bool) {
	switch {
	case c >= '0' && c <= '9':
		return c - '0', true
	case c >= 'a' && c <= 'f':
		return c - 'a' + 10, true
	case c >= 'A' && c <= 'F':
		return c - 'A' + 10, true
	}
	return 0, false
}
